### PR TITLE
✨  Adding yarn support

### PR DESCRIPTION
**Pull request by ihatem**
A little PR to support yarn. 

Usage: 
```bash
$ create-express-api name-of-api [-y|--yarn]  
```

### CODE REVIEW

**Review by ishan123456789 — COMMENTED** [review]
I don't see any valid change besides the Readme change rest all are formatting and your .gitignore  ignores *.lock which should always be committed.

**Comment by ihatem** [comment]
> I don't see any valid change besides the Readme change rest all are formatting and your .gitignore ignores *.lock which should always be committed.

did you check the `index.js` file ?

**Comment by ishan123456789** [comment]
Got it there are many formatting changes so I just skimmed through ignoring the relevant changes

**Comment by w3cj** [comment]
The repo that is cloned uses a package-lock.json
For now, if someone wants to use yarn, they can after cloning.

**Pull request closed without merging**
